Building configuration...

Current configuration:
!
frr version 8.4_git
frr defaults traditional
hostname spine2
no ipv6 forwarding
!
interface eth1
 ip address 10.0.3.1/30
exit
!
interface eth2
 ip address 10.0.4.1/30
exit
!
interface lo
 ip address 2.2.2.2/32
exit
!
router bgp 65000
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 neighbor 10.0.3.2 remote-as 65001
 neighbor 10.0.4.2 remote-as 65002
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
exit
!
end
