frr version 8.4_git
frr defaults traditional
hostname spine1
no ipv6 forwarding
!
interface eth1
 ip address 10.0.1.1/30
exit
!
interface eth2
 ip address 10.0.2.1/30
exit
!
interface lo
 ip address 1.1.1.1/32
exit
!
router bgp 65000
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 neighbor 10.0.1.2 remote-as 65001
 neighbor 10.0.1.2 timers 3 9
 neighbor 10.0.2.2 remote-as 65002
 neighbor 10.0.2.2 timers 3 9
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor 10.0.1.2 soft-reconfiguration inbound
  neighbor 10.0.1.2 route-map ALLOW-ALL in
  neighbor 10.0.1.2 route-map ALLOW-ALL out
  neighbor 10.0.2.2 soft-reconfiguration inbound
  neighbor 10.0.2.2 route-map ALLOW-ALL in
  neighbor 10.0.2.2 route-map ALLOW-ALL out
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 10.0.1.2 activate
  neighbor 10.0.1.2 route-map ALLOW-ALL in
  neighbor 10.0.1.2 route-map ALLOW-ALL out
  neighbor 10.0.2.2 activate
  neighbor 10.0.2.2 route-map ALLOW-ALL in
  neighbor 10.0.2.2 route-map ALLOW-ALL out
 exit-address-family
exit
!
route-map ALLOW-ALL permit 10
exit
!
